accounts/urls.py
from django.urls import path
from . import views


app_name= "accounts"

urlpatterns = [
    path('login/', views.login_view, name= 'login'),
    path('logout/', views.logout_view, name= 'logout'),
    path('register/', views.register_view, name= 'register'),
]

articles/urls.py
from django.urls import path
from . import views


app_name= "articles"

urlpatterns = [
    path('', views.index, name= 'index'),
    path('create', views.create, name= 'create'),
    path('search', views.search, name= 'search'),
    path('<int:id>/show', views.show, name= 'show'),
    path('<int:id>/edit', views.edit, name= 'edit'),
    path('<int:id>/delete', views.delete, name= 'delete'),
]

pages/urls.py
from django.urls import path
from . import views


app_name= "pages"

urlpatterns = [
    path('', views.index, name= 'index'),
    path('about', views.about, name= 'about'),
    path('contact', views.contact, name= 'contact'),
    path('team', views.team, name= 'team'),
]

trydjango/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    # path('', articles_views.index, name= 'articles_index'),
    path('', include("pages.urls")),
    path('articles/', include("articles.urls")),
    path('accounts/', include("accounts.urls")),

    # Admin Paths
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.db.models.signals import pre_save, post_save
# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length= 100)
    slug = models.SlugField(null= True, blank= True)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add= True)
    updated_at = models.DateTimeField(auto_now= True)
    published_at = models.DateTimeField(auto_now=False, auto_now_add=False, default= timezone.now)

    def __str__(self) -> str:
        return self.title

    def save(self, *args, **kwargs):
        if self.slug is None:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

articles/forms.py
from django import forms
from django.db.models import fields
from .models import Article

class ArticleModelForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title", "content", "published_at"]

    def clean(self):
        title = self.cleaned_data.get("title")
        content = self.cleaned_data.get("content")
        if title.endswith("Awesome"):
            self.add_error("title", "Title can't end with 'Awesome' ")

        if content.endswith("Awesome"):
            self.add_error("content", "Content can't contain 'Awesome' ")
        return self.cleaned_data

class ArticleForm(forms.Form):
    title = forms.CharField()
    content = forms.CharField()

    # def clean_title(self):
    #     title = self.cleaned_data.get("title")
    #     if title.endswith("Awesome"):
    #         #self.add_error("title", "Title can't end with 'Awesome' ")
    #         raise forms.ValidationError("Error")
    #     return title
    
    # def clean_content(self):
    #     content = self.cleaned_data.get("content")
    #     if content.endswith("Awesome"):
    #         raise forms.ValidationError("Error")
    #         #self.add_error("content", "Content can't contain 'Awesome' ")
    #     return content
    

    def clean(self):
        title = self.cleaned_data.get("title")
        content = self.cleaned_data.get("content")
        if title.endswith("Awesome"):
            self.add_error("title", "Title can't end with 'Awesome' ")

        if content.endswith("Awesome"):
            self.add_error("content", "Content can't contain 'Awesome' ")
        return self.cleaned_data

accounts/views.py
from django import forms
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import logout, login, authenticate
# Create your views here.

def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data = request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect("/")
    else:
        form = AuthenticationForm(request)
    context = {
        "form": form
    }
    return render(request, "accounts/login.html", context)


def logout_view(request):
    if request.method == "POST":
        if request.user.is_authenticated:
            logout(request)
            return redirect("/")
        else:
            return redirect("/")
    else:
        return redirect("/")


def register_view(request):
    form = UserCreationForm(request.POST or None)
    context = {
        "form" : form
    }
    if form.is_valid():
        user = form.save()
        return redirect("/")
    return render(request, "accounts/register.html", context)

articles/views.py
from django import http
from django.shortcuts import render, get_object_or_404
from .models import Article
from django.contrib.auth.decorators import login_required
from .forms import ArticleForm, ArticleModelForm

# Create your views here.
def index(request):
    article_list = Article.objects.all()
    context = {
        "article_list": article_list,
    }

    return render(request, "articles/index.html", context)

def search(request):
    search = request.GET

    queryset = get_object_or_404(Article, id= search.get("query"))
    context = {
        'article': queryset,
    }
    return render(request, "articles/search.html", context)

@login_required
def create(request):
    #form = ArticleForm(request.POST or None)
    form = ArticleModelForm(request.POST or None)
    context = {
        "form": form,
    }
    if form.is_valid():
        # print(form.cleaned_data)
        article = form.save()
        context["article"]= article
        context["is_created"]= True

    return render(request, "articles/create.html", context)



def show(request, id):
   pass

@login_required
def edit(request, id):
   pass

@login_required
def delete(request, id):
    pass

pages/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, "pages/index.html")

def about(request):
    return render(request, "pages/about.html")

def contact(request):
    return render(request, "pages/contact.html")

def team(request):
    return render(request, "pages/team.html")

templates/accounts/login.html
{% extends 'base.html' %}

{% block title %} Login to your account {% endblock %}

{% block content %}
    {% if not user.is_authenticated %}
        <form action="{% url 'accounts:login' %}" method="POST">
            {% csrf_token %}
            <h3>Login to your account</h3>
            {{ form.as_p }}
            <input type="submit" value="Login">
        </form><br><br>
    {% else %}
        <p>You are already logged in, if you want to logout try from here <a href="javascript: document.getElementById('logout_form').submit()">Logout</a></p>
    {% endif %}

    {% if user.is_authenticated %}
    <form style="display: none" id="logout_form" action="{% url 'accounts:logout' %}" method="POST">
        {% csrf_token %}
    </form><br><br>
    {% endif %}

{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}

{% block title %} Register New User {% endblock %}

{% block content %}
    <form action="{% url 'accounts:register' %}" method="POST">
        {% csrf_token %}
        <h3>Register new account</h3>
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>
{% endblock %}

templates/articles/create.html
{% extends 'base.html' %}

{% block title %} Articles - Create New {% endblock %}

{% block content %}
    <form action="{% url 'articles:create' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create New">
    </form>
    <!-- {% if not is_created %}
        <form action="{% url 'articles:create' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Create New">
        </form>
    {% else %}
        <p>Your article was created successfully.</p>
        {{ article.id }}
        <a href="{% url 'articles:show' article.id %}">{{ article.title }}</a>
    {% endif %} -->

{% endblock %}

templates/articles/index.html
{% extends 'base.html' %}

{% block title %} Articles - All {% endblock %}

{% block content %}
    <a href="{% url 'articles:create' %}">Create New</a><br>
    {% if article_list %}    
    <ul>
        {% for article in article_list  %}
            <li><a href="{% url 'articles:show' article.id %}">{{ article.title }}</a></li>
        {% endfor %}
    </ul>
    {% endif %}

{% endblock %}

templates/articles/search.html
{% extends 'base.html' %}

{% block title %} Search for an article {% endblock %}

{% block content %}
    <h1>Search Results</h1>
    {% if article %}    
        <h4>{{ article.title }}</h4>
        <p>{{ article.content }}</p>
    {% endif %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %} {% endblock %}</title>
    </head>
    <body>
        <form action="{% url 'articles:search' %}" method="get">
            <h3>Search for an article</h3>
            <input type="text" name="query">
            <input type="submit" value="Search">
        </form><br><br>
        {% block content %} {% endblock %}
    </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
<h1>{{article_obj.title}}</h1><p>{{article_obj.content}}</p>
{% endblock %}

templates/pages/about.html
{% extends 'base.html' %}

{% block title %} About {% endblock %}

{% block content %}
<h1>About</h1>
{% endblock %}

templates/pages/contact.html
{% extends 'base.html' %}

{% block title %} Contact {% endblock %}

{% block content %}
<h1>Contact</h1>
{% endblock %}

templates/pages/index.html
{% extends 'base.html' %}

{% block title %} Index {% endblock %}

{% block content %}
<h1>Index</h1>
{% endblock %}

templates/pages/team.html
{% extends 'base.html' %}

{% block title %} Team {% endblock %}

{% block content %}
<h1>Team</h1>
{% endblock %}